// GENERATED by scripts/generate-labels.mjs from evidence/generated/ui-evidence-matrix.json
// (itself produced deterministically from the shipped Grok Bot 0.24 renderer
// bundles by scripts/analyze-renderer.mjs). Do not hand-edit strings or
// provenance; regenerate instead. Clean-room ids are ours; text/key/chunks are
// artifact-recovered (confidence A). Geometry/layout is NOT claimed here.
// Trailing-space labels ("Updates follow the ") are interpolation prefixes in
// the shipped message catalog.

export interface Label {
  readonly surface: string;
  /** Exact shipped string (confidence A). */
  readonly text: string;
  /** i18n message id in the shipped bundle, or "(string-literal)". */
  readonly key: string;
  /** Provenance chunk sample(s) in dist/renderer/assets. */
  readonly chunks: readonly string[];
}

export const LABELS = {
  // sidebar
  sidebar: { surface: "sidebar", text: "Sidebar", key: "uWi2Q+", chunks: ["index-Bbahbz13.js"] },
  collapseSidebar: { surface: "sidebar", text: "Collapse sidebar", key: "mkMLq4", chunks: ["index-Bbahbz13.js"] },
  expandSidebar: { surface: "sidebar", text: "Expand sidebar", key: "tugdy6", chunks: ["index-Bbahbz13.js"] },
  resizeSidebar: { surface: "sidebar", text: "Resize sidebar", key: "cyFaZJ", chunks: ["index-Bbahbz13.js"] },
  searchBots: { surface: "sidebar", text: "Search Bots", key: "YjO4Og", chunks: ["index-Bbahbz13.js"] },
  newSection: { surface: "sidebar", text: "New section", key: "SagCAA", chunks: ["index-Bbahbz13.js"] },
  renameSection: { surface: "sidebar", text: "Rename section", key: "wcgxIB", chunks: ["index-Bbahbz13.js"] },
  moveToSection: { surface: "sidebar", text: "Move to section", key: "GYkPNu", chunks: ["index-Bbahbz13.js"] },
  sectionActions: { surface: "sidebar", text: "Section actions", key: "8gtQoG", chunks: ["index-Bbahbz13.js"] },
  hideFromSidebar: { surface: "sidebar", text: "Hide from sidebar", key: "tIf/jS", chunks: ["index-Bbahbz13.js"] },
  showHiddenBots: { surface: "sidebar", text: "Show Hidden Bots", key: "f3HCFf", chunks: ["index-Bbahbz13.js"] },
  hiddenBots: { surface: "sidebar", text: "Hidden Bots", key: "JuesWZ", chunks: ["index-Bbahbz13.js"] },
  newBotOrChannel: { surface: "sidebar", text: "New Bot or Channel", key: "VKOgAI", chunks: ["index-Bbahbz13.js"] },
  channels: { surface: "sidebar", text: "Channels", key: "lfFsZ4", chunks: ["index-Bbahbz13.js"] },
  groups: { surface: "sidebar", text: "Groups", key: "zhrjek", chunks: ["index-Bbahbz13.js"] },
  // onboarding.tool-selector
  whatDaily: { surface: "onboarding.tool-selector", text: "What do you use every day?", key: "v0U/Mf", chunks: ["index-Bbahbz13.js"] },
  roleMarketingAnalyst: { surface: "onboarding.tool-selector", text: "Marketing Analyst", key: "fTQX5K", chunks: ["index-Bbahbz13.js"] },
  roleOutreach: { surface: "onboarding.tool-selector", text: "Outreach", key: "gNzMwN", chunks: ["core-293kCc7F.js", "core-AD8lWP0_.js", "core-BUJ8djP-.js"] },
  roleQaEngineer: { surface: "onboarding.tool-selector", text: "QA Engineer", key: "7hMgfB", chunks: ["index-Bbahbz13.js"] },
  roleResearcher: { surface: "onboarding.tool-selector", text: "Researcher", key: "eoQPwJ", chunks: ["index-Bbahbz13.js"] },
  roleExpenseAuditor: { surface: "onboarding.tool-selector", text: "Expense Auditor", key: "v5aXcN", chunks: ["index-Bbahbz13.js"] },
  roleWinLossAnalyst: { surface: "onboarding.tool-selector", text: "Win-Loss Analyst", key: "8zvlyI", chunks: ["index-Bbahbz13.js"] },
  create: { surface: "onboarding.tool-selector", text: "Create", key: "hYgDIe", chunks: ["index-Bbahbz13.js"] },
  meetTeammate: { surface: "onboarding.tool-selector", text: "Meet a future teammate", key: "XRN0th", chunks: ["index-Bbahbz13.js"] },
  createFirstBot: { surface: "onboarding.tool-selector", text: "Create your first Bot", key: "El3CK2", chunks: ["index-Bbahbz13.js"] },
  nameYourBot: { surface: "onboarding.tool-selector", text: "Name your Bot", key: "2DQ7aH", chunks: ["index-Bbahbz13.js"] },
  nameTeammate: { surface: "onboarding.tool-selector", text: "Name a teammate and describe what they should do", key: "8R04P/", chunks: ["index-Bbahbz13.js"] },
  whatHelpWith: { surface: "onboarding.tool-selector", text: "What should this Bot help with?", key: "VZSV/i", chunks: ["index-Bbahbz13.js"] },
  describeBot: { surface: "onboarding.tool-selector", text: "Describe what your Bot does", key: "qmM+6N", chunks: ["index-Bbahbz13.js"] },
  // create-bot.avatar
  editAvatar: { surface: "create-bot.avatar", text: "Edit Avatar", key: "5XRPbV", chunks: ["index-Bbahbz13.js"] },
  avatarEditor: { surface: "create-bot.avatar", text: "Avatar editor", key: "p9Xy+W", chunks: ["index-Bbahbz13.js"] },
  avatarSource: { surface: "create-bot.avatar", text: "Avatar source", key: "ciFwRi", chunks: ["index-Bbahbz13.js"] },
  characterShape: { surface: "create-bot.avatar", text: "Character shape", key: "dcNGHT", chunks: ["index-Bbahbz13.js"] },
  shuffle: { surface: "create-bot.avatar", text: "Shuffle", key: "gH5Gbn", chunks: ["index-Bbahbz13.js"] },
  describeAvatar: { surface: "create-bot.avatar", text: "Describe your avatar", key: "IVpf8Z", chunks: ["index-Bbahbz13.js"] },
  describeAvatarPh: { surface: "create-bot.avatar", text: "Describe your avatar…", key: "7KrBp7", chunks: ["index-Bbahbz13.js"] },
  generatingAvatar: { surface: "create-bot.avatar", text: "Generating avatar", key: "lhKkFq", chunks: ["index-Bbahbz13.js"] },
  setAvatar: { surface: "create-bot.avatar", text: "Set avatar", key: "eCtMfe", chunks: ["index-Bbahbz13.js"] },
  editBotAvatar: { surface: "create-bot.avatar", text: "Edit Bot avatar", key: "fopc9x", chunks: ["index-Bbahbz13.js"] },
  // chat.composer
  search: { surface: "chat.composer", text: "Search", key: "A1taO8", chunks: ["index-Bbahbz13.js"] },
  noToolsMatch: { surface: "chat.composer", text: "No tools match “", key: "+epf7J", chunks: ["index-Bbahbz13.js"] },
  send: { surface: "chat.composer", text: "Send", key: "JlFcis", chunks: ["index-Bbahbz13.js"] },
  // bot-details
  botSettings: { surface: "bot-details", text: "Bot settings", key: "q/EMCC", chunks: ["index-Bbahbz13.js"] },
  instructions: { surface: "bot-details", text: "Instructions", key: "NxHkkp", chunks: ["core-CVK-myG_.js", "index-Bbahbz13.js"] },
  model: { surface: "bot-details", text: "Model", key: "scu3wk", chunks: ["index-Bbahbz13.js", "settings-DoLTQOmL.js"] },
  name: { surface: "bot-details", text: "Name", key: "6YtxFj", chunks: ["agents-PuDzmvDC.js", "core-LZzLS_TH.js", "index-Bbahbz13.js"] },
  routinesBlurb: { surface: "bot-details", text: "Routines are recurring tasks this Bot runs on a schedule.", key: "zwXXir", chunks: ["index-Bbahbz13.js"] },
  // agent-computer
  agentComputer: { surface: "agent-computer", text: "Agent Computer", key: "(string-literal)", chunks: ["core-CVK-myG_.js", "core-LZzLS_TH.js", "index-Bbahbz13.js"] },
  grokComputer: { surface: "agent-computer", text: "Grok Bot's Computer", key: "iXLVub", chunks: ["index-Bbahbz13.js"] },
  takeOver: { surface: "agent-computer", text: "Take over", key: "yqwjpd", chunks: ["index-Bbahbz13.js"] },
  openComputer: { surface: "agent-computer", text: "Open computer", key: "Cfg0eW", chunks: ["index-Bbahbz13.js"] },
  computerPreview: { surface: "agent-computer", text: "Computer preview", key: "PVszY+", chunks: ["index-Bbahbz13.js"] },
  runsLocal: { surface: "agent-computer", text: "Runs on your local computer", key: "YkK+co", chunks: ["index-Bbahbz13.js"] },
  runsCloud: { surface: "agent-computer", text: "Runs on Grok Bot's computer", key: "bNZVxg", chunks: ["index-Bbahbz13.js"] },
  // teach-a-task
  teachTask: { surface: "teach-a-task", text: "Teach a task", key: "yrMloC", chunks: ["index-Bbahbz13.js"] },
  // routines.editor
  routines: { surface: "routines.editor", text: "Routines", key: "dmYV6f", chunks: ["agents-CMu69s5c.js", "core-CVK-myG_.js", "index-Bbahbz13.js"] },
  createRoutine: { surface: "routines.editor", text: "Create Routine", key: "OxvEPW", chunks: ["index-Bbahbz13.js"] },
  routine: { surface: "routines.editor", text: "Routine", key: "aAnCaW", chunks: ["agents-CMu69s5c.js", "agents-PuDzmvDC.js", "chat-BLIGAYUl.js"] },
  nameThisRoutine: { surface: "routines.editor", text: "Name this routine", key: "1BsqCM", chunks: ["index-Bbahbz13.js"] },
  triggers: { surface: "routines.editor", text: "Triggers", key: "34nxyb", chunks: ["index-Bbahbz13.js"] },
  addTrigger: { surface: "routines.editor", text: "Add trigger", key: "tVVIF0", chunks: ["index-Bbahbz13.js"] },
  triggerFields: { surface: "routines.editor", text: "Trigger fields", key: "/MEPLt", chunks: ["index-Bbahbz13.js"] },
  triggerSource: { surface: "routines.editor", text: "Trigger source", key: "hIigym", chunks: ["index-Bbahbz13.js"] },
  backToRoutines: { surface: "routines.editor", text: "Back to Routines", key: "QH9fQa", chunks: ["index-Bbahbz13.js"] },
  afterSave: { surface: "routines.editor", text: "Available after the routine is saved", key: "TwyiXx", chunks: ["index-Bbahbz13.js"] },
  routineRunsPrompt: { surface: "routines.editor", text: "What should this routine do each time it runs?", key: "vkUsZj", chunks: ["index-Bbahbz13.js"] },
  // plugins
  plugins: { surface: "plugins", text: "Plugins", key: "ohUJJM", chunks: ["agents-9VAqkDGo.js", "agents-CMu69s5c.js", "agents-PuDzmvDC.js"] },
  plugin: { surface: "plugins", text: "Plugin", key: "fOuPPd", chunks: ["chat-BLIGAYUl.js", "chat-DVITqTru.js", "chat-GljIqmTW.js"] },
  uninstall: { surface: "plugins", text: "Uninstall", key: "fo0VXg", chunks: ["index-Bbahbz13.js"] },
  install: { surface: "plugins", text: "Install", key: "TKQ7K+", chunks: ["index-Bbahbz13.js"] },
  // settings.general
  settings: { surface: "settings.general", text: "Settings", key: "Tz0i8g", chunks: ["index-Bbahbz13.js"] },
  general: { surface: "settings.general", text: "General", key: "Weq9zb", chunks: ["index-Bbahbz13.js", "settings-DUOpzRFa.js"] },
  localToolPermissions: { surface: "settings.general", text: "Local tool permissions", key: "3e6/vm", chunks: ["index-Bbahbz13.js"] },
  localToolPermission: { surface: "settings.general", text: "Local tool permission", key: "qM5wI6", chunks: ["index-Bbahbz13.js"] },
  // settings.appearance
  appearance: { surface: "settings.appearance", text: "Appearance", key: "aAIQg2", chunks: ["index-Bbahbz13.js"] },
  theme: { surface: "settings.appearance", text: "Theme", key: "FEr96N", chunks: ["index-Bbahbz13.js"] },
  themeDark: { surface: "settings.appearance", text: "Theme: Dark", key: "0RUFwi", chunks: ["index-Bbahbz13.js"] },
  themeLight: { surface: "settings.appearance", text: "Theme: Light", key: "3XHx94", chunks: ["index-Bbahbz13.js"] },
  themeSystem: { surface: "settings.appearance", text: "Theme: System", key: "NMdQdl", chunks: ["index-Bbahbz13.js"] },
  systemDefault: { surface: "settings.appearance", text: "System Default", key: "9YHrNC", chunks: ["index-Bbahbz13.js"] },
  light: { surface: "settings.appearance", text: "Light", key: "1njn7W", chunks: ["index-Bbahbz13.js"] },
  dark: { surface: "settings.appearance", text: "Dark", key: "pvnfJD", chunks: ["index-Bbahbz13.js"] },
  system: { surface: "settings.appearance", text: "System", key: "D+NlUC", chunks: ["index-Bbahbz13.js", "settings-BYiFjrlH.js", "settings-DoLTQOmL.js"] },
  // settings.updates
  updates: { surface: "settings.updates", text: "Updates", key: "qIrtcK", chunks: ["core-LZzLS_TH.js", "index-Bbahbz13.js", "settings-BYiFjrlH.js"] },
  checkForUpdates: { surface: "settings.updates", text: "Check for Updates", key: "ETzTLS", chunks: ["index-Bbahbz13.js"] },
  restartToUpdate: { surface: "settings.updates", text: "Restart to update", key: "FzpXvM", chunks: ["index-Bbahbz13.js"] },
  updateReady: { surface: "settings.updates", text: "Update ready", key: "RiNIn5", chunks: ["index-Bbahbz13.js"] },
  newUpdateAvailable: { surface: "settings.updates", text: "New update available", key: "OaoXkB", chunks: ["index-Bbahbz13.js"] },
  updatesFollowTrack: { surface: "settings.updates", text: "Updates follow the ", key: "A7fKzC", chunks: ["index-Bbahbz13.js"] },
  version: { surface: "settings.updates", text: "Version ", key: "YYdC3A", chunks: ["core-CVK-myG_.js", "core-LZzLS_TH.js", "index-Bbahbz13.js"] },
  // hidden-chats
  hcShowHiddenBots: { surface: "hidden-chats", text: "Show Hidden Bots", key: "f3HCFf", chunks: ["index-Bbahbz13.js"] },
  hcHiddenBots: { surface: "hidden-chats", text: "Hidden Bots", key: "JuesWZ", chunks: ["index-Bbahbz13.js"] },
  hcAllBotsCount: { surface: "hidden-chats", text: "All Bots (", key: "vCdljE", chunks: ["index-Bbahbz13.js"] },
  hcHiddenBlurb: { surface: "hidden-chats", text: "Hidden Bots stay active and keep their history, they just don't show in the sidebar.", key: "IB0Mqd", chunks: ["index-Bbahbz13.js"] },
  hcAllBotsHidden: { surface: "hidden-chats", text: "All bots are hidden", key: "SGMB5I", chunks: ["index-Bbahbz13.js"] },
  // org-chart
  orgChart: { surface: "org-chart", text: "Org chart", key: "g8mQGH", chunks: ["index-Bbahbz13.js"] },
  closeOrgChart: { surface: "org-chart", text: "Close org chart", key: "vYyH59", chunks: ["index-Bbahbz13.js"] },
  orgChartDetails: { surface: "org-chart", text: "Org chart details", key: "g+dQDw", chunks: ["index-Bbahbz13.js"] },
  botNetwork: { surface: "org-chart", text: "Bot network", key: "7IF48T", chunks: ["index-Bbahbz13.js"] },
  noBotsYetNetwork: { surface: "org-chart", text: "No Bots yet. Create a few teammates and the network draws itself.", key: "81tEjQ", chunks: ["index-Bbahbz13.js"] },
  networkLegend: { surface: "org-chart", text: "Bots and groups, linked by who has messaged whom (solid) and group membership (dashed). Click a node to open it.", key: "w3HQhq", chunks: ["index-Bbahbz13.js"] },
  // command-palette
  paletteSearch: { surface: "command-palette", text: "Search", key: "A1taO8", chunks: ["index-Bbahbz13.js"] },
  suggestions: { surface: "command-palette", text: "Suggestions", key: "8J32PY", chunks: ["core-CVK-myG_.js", "index-Bbahbz13.js"] },
  // approvals
  approvalNeeded: { surface: "approvals", text: "Approval needed", key: "az21Qe", chunks: ["index-Bbahbz13.js"] },
  approve: { surface: "approvals", text: "Approve", key: "Z7ZXbT", chunks: ["index-Bbahbz13.js"] },
  deny: { surface: "approvals", text: "Deny", key: "cFCKYZ", chunks: ["index-Bbahbz13.js"] },
  denyOnce: { surface: "approvals", text: "Deny once", key: "rek4Fs", chunks: ["index-Bbahbz13.js"] },
  alwaysAllow: { surface: "approvals", text: "Always allow", key: "NoKBgy", chunks: ["index-Bbahbz13.js"] },
  alwaysAllowed: { surface: "approvals", text: "Always allowed", key: "gBhy/k", chunks: ["index-Bbahbz13.js"] },
  autoReviewApproval: { surface: "approvals", text: "Auto-review approval", key: "U3Kd/c", chunks: ["index-Bbahbz13.js"] },
  // secret-requests
  requestSent: { surface: "secret-requests", text: "Request sent. Once the host approves, ", key: "1tlhVf", chunks: ["index-Bbahbz13.js"] },
  couldNotStoreSecret: { surface: "secret-requests", text: "Could not store the secret", key: "pKu300", chunks: ["index-Bbahbz13.js"] },
  shareSecretPrefix: { surface: "secret-requests", text: "Share ", key: "xy569a", chunks: ["index-Bbahbz13.js"] },
} as const satisfies Record<string, Label>;

export type LabelId = keyof typeof LABELS;

/** Look up an artifact-backed label by id. */
export function t(id: LabelId): string {
  return LABELS[id].text;
}

/** All labels grouped by surface (validator/test convenience). */
export function labelsBySurface(): Map<string, Label[]> {
  const m = new Map<string, Label[]>();
  for (const l of Object.values(LABELS)) {
    if (!m.has(l.surface)) m.set(l.surface, []);
    m.get(l.surface)!.push(l);
  }
  return m;
}
